from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class VariantSpec:
    name: str
    display_name: str
    family: str
    palette: str
    scene: str
    scene_recipe: str
    motifs: tuple[str, ...]
    dominant_geometry: tuple[str, ...]
    movement_type: tuple[str, ...]
    camera_roles: tuple[str, ...]
    audio_mappings: tuple[str, ...]
    persistent_elements: tuple[str, ...]
    suitable_presets: tuple[str, ...]
    speed: float = 1.0
    density: float = 1.0
    structure: float = 1.0
    atmosphere: float = 1.0


def _spec(
    name: str,
    display_name: str,
    family: str,
    palette: str,
    scene: str,
    motifs: tuple[str, ...],
    dominant_geometry: tuple[str, ...],
    movement_type: tuple[str, ...],
    camera_roles: tuple[str, ...],
    suitable_presets: tuple[str, ...],
    *,
    speed: float = 1.0,
    density: float = 1.0,
    structure: float = 1.0,
    atmosphere: float = 1.0,
) -> VariantSpec:
    family_audio = {
        "transit": ("kick pushes camera", "bass drives passing depth", "highs flicker signs"),
        "cyber_urban": ("bass deepens skyline drift", "mids shift tower rhythm", "highs flicker signs"),
        "water_glass": ("bass undulates slabs", "mids sway glass forms", "highs add glints and bubbles"),
        "ui_computer": ("beat pops panels", "bass zooms routes and aisles", "highs sparkle CRT edges"),
        "nature_weather": ("bass swells terrain or water", "mids drift clouds and plants", "highs shimmer horizon details"),
        "space_cosmic": ("pads drift structures", "bass rotates stations", "highs sparkle stars and relays"),
        "abstract_geometry": ("beat rotates solids", "bass pushes scale and depth", "highs shimmer edges"),
        "architecture_interior": ("bass shifts room depth", "mids sway fixtures", "highs brighten trims"),
    }
    family_persistent = {
        "transit": ("rails", "fog", "light rows"),
        "cyber_urban": ("fog", "sign blocks", "particles"),
        "water_glass": ("reflections", "mist", "panel glows"),
        "ui_computer": ("scanlines", "route lines", "ui panels"),
        "nature_weather": ("mist", "horizon bands", "soft particles"),
        "space_cosmic": ("stars", "mist", "ring traces"),
        "abstract_geometry": ("rings", "mist", "reflection streaks"),
        "architecture_interior": ("hall fog", "floor bands", "fixture glow"),
    }
    return VariantSpec(
        name=name,
        display_name=display_name,
        family=family,
        palette=palette,
        scene=scene,
        scene_recipe=name,
        motifs=motifs,
        dominant_geometry=dominant_geometry,
        movement_type=movement_type,
        camera_roles=camera_roles,
        audio_mappings=family_audio[family],
        persistent_elements=family_persistent[family],
        suitable_presets=suitable_presets,
        speed=speed,
        density=density,
        structure=structure,
        atmosphere=atmosphere,
    )


TRANSIT_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("mountain_tram", "Mountain Tram", "transit", "bios_ocean", "transit", ("tram cabin", "suspension pylons", "mountain slabs", "rail cables"), ("rails", "columns", "pyramids", "signage_blocks"), ("lateral_drift", "parallax", "depth_pass"), ("side_tracking_shot", "high_overlook_drift", "close_object_pass"), ("lofi", "night_transit"), speed=0.92, structure=1.18),
    _spec("airport_moving_walkway", "Airport Moving Walkway", "transit", "bios_ocean", "transit", ("moving walkway", "terminal glass", "gate pylons", "arrival signs"), ("rails", "floating_panels", "columns", "signage_blocks"), ("depth_pass", "slide_past", "rise_fall"), ("wide_crane_rise", "diagonal_dolly", "long_horizon_glide"), ("lofi", "night_transit"), speed=0.98, structure=1.12),
    _spec("highway_toll_gates", "Highway Toll Gates", "transit", "neon_nocturne", "highway", ("toll arches", "lane wedges", "road beacons", "sign gantries"), ("arches", "rails", "signage_blocks", "columns"), ("depth_pass", "slide_past", "slow_rotate"), ("reverse_pullback", "low_flythrough", "crossing_parallax_pan"), ("night_transit",), speed=1.08, structure=1.2),
    _spec("elevated_train_depot", "Elevated Train Depot", "transit", "terminal_mist", "transit", ("depot bays", "service gantries", "parked pods", "track ladders"), ("rails", "cuboids", "arches", "pods"), ("parallax", "rise_fall", "depth_pass"), ("wide_crane_rise", "side_tracking_shot", "high_overlook_drift"), ("night_transit", "lofi"), speed=0.9, structure=1.2),
    _spec("night_bus_terminal", "Night Bus Terminal", "transit", "rain_alley", "transit", ("bus bays", "roof canopies", "lane bollards", "departure boards"), ("arches", "cuboids", "signage_blocks", "rails"), ("slide_past", "lateral_drift", "parallax"), ("wide_crane_rise", "crossing_parallax_pan", "close_object_pass"), ("night_transit", "lofi"), speed=0.88, structure=1.08),
    _spec("ferry_terminal", "Ferry Terminal", "transit", "sunken_plaza", "transit", ("ferry ramp", "water edge", "pier lights", "ticket canopy"), ("ramps", "water_slabs", "columns", "signage_blocks"), ("undulate", "parallax", "depth_pass"), ("long_horizon_glide", "side_tracking_shot", "wide_crane_rise"), ("lofi",), speed=0.82, structure=1.05),
    _spec("tunnel_interchange", "Tunnel Interchange", "transit", "neon_nocturne", "corridor", ("split tunnel", "overhead signs", "merge lanes", "rib arches"), ("arches", "rails", "signage_blocks", "ring_gates"), ("depth_pass", "spiral", "slide_past"), ("low_flythrough", "diagonal_dolly", "spiral_approach"), ("night_transit",), speed=1.1, structure=1.22),
    _spec("parking_garage_descent", "Parking Garage Descent", "transit", "chrome_dream", "transit", ("descending ramps", "ceiling strips", "concrete decks", "turn arrows"), ("ramps", "columns", "cuboids", "signage_blocks"), ("depth_pass", "rise_fall", "parallax"), ("reverse_pullback", "diagonal_dolly", "low_flythrough"), ("night_transit", "high_trust_society"), speed=0.94, structure=1.18),
    _spec("coastal_expressway", "Coastal Expressway", "transit", "sunken_plaza", "highway", ("sea wall", "elevated lanes", "guard rails", "salt haze"), ("rails", "water_slabs", "arches", "signage_blocks"), ("depth_pass", "undulate", "parallax"), ("long_horizon_glide", "wide_crane_rise", "reverse_pullback"), ("lofi",), speed=1.02, structure=1.08),
    _spec("viaduct_crossing", "Viaduct Crossing", "transit", "terminal_mist", "transit", ("crossing tracks", "viaduct towers", "deck shadows", "signal frames"), ("rails", "towers", "arches", "columns"), ("parallax", "depth_pass", "lateral_drift"), ("crossing_parallax_pan", "high_overlook_drift", "wide_crane_rise"), ("night_transit", "lofi"), speed=0.96, structure=1.2),
    _spec("cargo_airfield_corridor", "Cargo Airfield Corridor", "transit", "bios_ocean", "transit", ("cargo carts", "hangar walls", "taxiway lights", "runway panels"), ("cuboids", "floating_panels", "rails", "columns"), ("slide_past", "depth_pass", "parallax"), ("diagonal_dolly", "low_flythrough", "side_tracking_shot"), ("night_transit",), speed=1.0, structure=1.1),
    _spec("monorail_switchyard", "Monorail Switchyard", "transit", "neon_nocturne", "transit", ("switch beams", "pod slips", "junction gates", "tower braces"), ("rails", "ring_gates", "pods", "towers"), ("depth_pass", "slow_rotate", "parallax"), ("spiral_approach", "side_tracking_shot", "high_overlook_drift"), ("night_transit", "lofi"), speed=1.06, structure=1.18),
    _spec("tram_platform_canopy", "Tram Platform Canopy", "transit", "frutiger_aero", "transit", ("platform canopy", "glass shelter", "line maps", "soft station lights"), ("columns", "floating_panels", "rails", "water_slabs"), ("slide_past", "lateral_drift", "rise_fall"), ("close_object_pass", "wide_crane_rise", "side_tracking_shot"), ("lofi",), speed=0.86, structure=1.08),
    _spec("causeway_bus_exchange", "Causeway Bus Exchange", "transit", "vapor_civic", "transit", ("coastal terminal", "bus rings", "lamps", "queue rails"), ("arches", "rails", "water_slabs", "signage_blocks"), ("parallax", "undulate", "slide_past"), ("wide_crane_rise", "crossing_parallax_pan", "long_horizon_glide"), ("lofi", "night_transit"), speed=0.84, structure=1.02),
    _spec("funicular_overlook", "Funicular Overlook", "transit", "sunken_plaza", "transit", ("funicular track", "slope pylons", "hill lights", "car silhouette"), ("rails", "columns", "pyramids", "signage_blocks"), ("rise_fall", "parallax", "depth_pass"), ("high_overlook_drift", "reverse_pullback", "side_tracking_shot"), ("lofi",), speed=0.78, structure=1.12),
    _spec("service_tunnel_loop", "Service Tunnel Loop", "transit", "terminal_mist", "corridor", ("maintenance loop", "cable trays", "wall bays", "marker posts"), ("arches", "cable_arcs", "cuboids", "rails"), ("depth_pass", "sway", "slide_past"), ("low_flythrough", "diagonal_dolly", "close_object_pass"), ("night_transit", "polygon_motion_gallery"), speed=1.04, structure=1.16),
)

CIVIC_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("city_hall_plaza", "City Hall Plaza", "cyber_urban", "vapor_civic", "plaza", ("civic podium", "flag poles", "plaza steps", "light towers"), ("columns", "ramps", "towers", "water_slabs"), ("parallax", "rise_fall", "long_glide"), ("wide_crane_rise", "long_horizon_glide", "crossing_parallax_pan"), ("lofi", "high_trust_society"), speed=0.84, structure=1.18),
    _spec("rooftop_water_tanks", "Rooftop Water Tanks", "cyber_urban", "bios_ocean", "city", ("tank silhouettes", "roof rails", "ladder cages", "city glow"), ("towers", "columns", "rails", "signage_blocks"), ("parallax", "slow_rotate", "lateral_drift"), ("high_overlook_drift", "side_tracking_shot", "reverse_pullback"), ("lofi",), speed=0.82, structure=1.12),
    _spec("telecom_tower_field", "Telecom Tower Field", "cyber_urban", "terminal_mist", "city", ("antenna masts", "relay dishes", "service huts", "warning lights"), ("antenna_arrays", "towers", "cuboids", "ring_gates"), ("sway", "rotate_satellite", "parallax"), ("high_overlook_drift", "wide_crane_rise", "spiral_approach"), ("lofi", "high_trust_society"), speed=0.88, structure=1.2),
    _spec("apartment_balcony_canyon", "Apartment Balcony Canyon", "cyber_urban", "rain_alley", "city", ("balcony stacks", "window towers", "air units", "narrow sky"), ("towers", "ramps", "signage_blocks", "floating_panels"), ("parallax", "slide_past", "lateral_drift"), ("close_object_pass", "crossing_parallax_pan", "reverse_pullback"), ("lofi",), speed=0.9, structure=1.18),
    _spec("covered_arcade_street", "Covered Arcade Street", "cyber_urban", "rain_alley", "city", ("covered street", "sign canopies", "shop blocks", "wet walkway"), ("arches", "signage_blocks", "columns", "water_slabs"), ("slide_past", "parallax", "undulate"), ("low_flythrough", "side_tracking_shot", "diagonal_dolly"), ("lofi", "cyber_aero_liquid"), speed=0.96, structure=1.16),
    _spec("riverside_promenade", "Riverside Promenade", "cyber_urban", "sunken_plaza", "city", ("river wall", "walk lights", "bridge spans", "tower horizon"), ("water_slabs", "rails", "arches", "towers"), ("undulate", "long_glide", "parallax"), ("long_horizon_glide", "wide_crane_rise", "crossing_parallax_pan"), ("lofi",), speed=0.78, structure=1.04),
    _spec("night_market_grid", "Night Market Grid", "cyber_urban", "neon_nocturne", "city", ("market stalls", "awning rows", "sign cubes", "crowd lanes"), ("signage_blocks", "cuboids", "floating_panels", "arches"), ("slide_past", "parallax", "lateral_drift"), ("side_tracking_shot", "close_object_pass", "wide_crane_rise"), ("lofi", "cyber_aero_liquid"), speed=0.98, structure=1.14),
    _spec("hillside_overlook", "Hillside Overlook", "cyber_urban", "sunken_plaza", "city", ("hill road", "tower horizon", "guard rails", "lamp strings"), ("rails", "towers", "pyramids", "water_slabs"), ("long_glide", "parallax", "depth_pass"), ("long_horizon_glide", "high_overlook_drift", "reverse_pullback"), ("lofi",), speed=0.74, structure=1.08),
    _spec("civic_steps_basin", "Civic Steps Basin", "cyber_urban", "vapor_civic", "plaza", ("civic stair basin", "water shelf", "light pillars", "lobby mass"), ("ramps", "water_slabs", "columns", "towers"), ("rise_fall", "undulate", "parallax"), ("wide_crane_rise", "diagonal_dolly", "long_horizon_glide"), ("lofi", "high_trust_society"), speed=0.82, structure=1.16),
    _spec("tram_viaduct_overlook", "Tram Viaduct Overlook", "cyber_urban", "terminal_mist", "city", ("tram viaduct", "tower blocks", "signal pylons", "drop shadows"), ("rails", "towers", "columns", "signage_blocks"), ("parallax", "depth_pass", "lateral_drift"), ("high_overlook_drift", "wide_crane_rise", "side_tracking_shot"), ("lofi", "night_transit"), speed=0.9, structure=1.18),
    _spec("administrative_roof_garden", "Administrative Roof Garden", "cyber_urban", "frutiger_aero", "plaza", ("roof garden", "planter cubes", "civic walls", "sky rails"), ("low_poly_plants", "cuboids", "rails", "floating_panels"), ("sway", "parallax", "long_glide"), ("high_overlook_drift", "wide_crane_rise", "close_object_pass"), ("lofi", "high_trust_society"), speed=0.76, structure=1.02),
    _spec("canal_side_walkway", "Canal Side Walkway", "cyber_urban", "sunken_plaza", "city", ("canal path", "bridge pylons", "water bands", "tower shimmer"), ("water_slabs", "rails", "columns", "towers"), ("undulate", "parallax", "slide_past"), ("crossing_parallax_pan", "long_horizon_glide", "side_tracking_shot"), ("lofi",), speed=0.8, structure=1.06),
    _spec("atrium_street_link", "Atrium Street Link", "cyber_urban", "frutiger_aero", "city", ("glass bridge street", "tower link", "entry pylons", "blue signage"), ("floating_panels", "arches", "towers", "signage_blocks"), ("parallax", "slide_past", "slow_rotate"), ("diagonal_dolly", "wide_crane_rise", "crossing_parallax_pan"), ("lofi", "cyber_aero_liquid"), speed=0.92, structure=1.12),
    _spec("waterfront_civic_ring", "Waterfront Civic Ring", "cyber_urban", "vapor_civic", "plaza", ("civic ring", "shore deck", "lamp arc", "reflective basin"), ("ring_gates", "water_slabs", "columns", "ramps"), ("undulate", "slow_rotate", "long_glide"), ("spiral_approach", "long_horizon_glide", "wide_crane_rise"), ("lofi",), speed=0.78, structure=1.1),
    _spec("service_rooftop_lanterns", "Service Rooftop Lanterns", "cyber_urban", "bios_ocean", "city", ("service roofs", "light boxes", "rail shadows", "machine blocks"), ("cuboids", "rails", "floating_panels", "antenna_arrays"), ("slide_past", "parallax", "sway"), ("close_object_pass", "high_overlook_drift", "crossing_parallax_pan"), ("lofi", "high_trust_society"), speed=0.86, structure=1.1),
    _spec("memorial_axis_plaza", "Memorial Axis Plaza", "cyber_urban", "vapor_civic", "plaza", ("long plaza axis", "memorial columns", "shallow mirror pool", "distant hall"), ("columns", "water_slabs", "ramps", "towers"), ("long_glide", "rise_fall", "parallax"), ("long_horizon_glide", "wide_crane_rise", "reverse_pullback"), ("lofi", "high_trust_society"), speed=0.74, structure=1.18),
)

WATER_GLASS_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("glass_elevator_shaft", "Glass Elevator Shaft", "water_glass", "frutiger_aero", "atrium", ("elevator tube", "glass ribs", "vertical cars", "sky reflections"), ("floating_panels", "columns", "water_slabs", "arches"), ("rise_fall", "slow_rotate", "parallax"), ("vertical_elevator_rise", "wide_crane_rise", "spiral_approach"), ("lofi", "frutiger_water"), speed=0.82, structure=1.16),
    _spec("indoor_waterfall_lobby", "Indoor Waterfall Lobby", "water_glass", "frutiger_aero", "atrium", ("water curtain", "planter columns", "bridge decks", "lobby glass"), ("water_slabs", "columns", "ramps", "low_poly_plants"), ("undulate", "rise_fall", "parallax"), ("wide_crane_rise", "diagonal_dolly", "long_horizon_glide"), ("lofi", "frutiger_water"), speed=0.8, structure=1.14),
    _spec("aquarium_tunnel", "Aquarium Tunnel", "water_glass", "frutiger_aero", "aquarium", ("aqua tunnel", "arched tanks", "bubble lights", "glass ribs"), ("ring_gates", "water_slabs", "arches", "floating_panels"), ("depth_pass", "undulate", "orbit"), ("low_flythrough", "spiral_approach", "side_tracking_shot"), ("frutiger_water", "cyber_aero_liquid"), speed=0.96, structure=1.14),
    _spec("shopping_mall_fountain_court", "Shopping Mall Fountain Court", "water_glass", "vapor_civic", "atrium", ("fountain court", "escalator ramps", "glass balustrades", "tile bands"), ("water_slabs", "ramps", "columns", "floating_panels"), ("jet_pulse", "rise_fall", "parallax"), ("wide_crane_rise", "side_tracking_shot", "close_object_pass"), ("lofi", "frutiger_water"), speed=0.84, structure=1.12),
    _spec("blue_sky_ui_garden", "Blue Sky UI Garden", "water_glass", "frutiger_aero", "garden", ("ui hedges", "aero slabs", "floating windows", "sky lawn"), ("low_poly_plants", "floating_panels", "water_slabs", "columns"), ("orbit", "sway", "rise_fall"), ("high_overlook_drift", "wide_crane_rise", "crossing_parallax_pan"), ("frutiger_water",), speed=0.76, structure=0.98),
    _spec("translucent_escalator_atrium", "Translucent Escalator Atrium", "water_glass", "frutiger_aero", "atrium", ("escalator ribbons", "glass planes", "atrium columns", "light wells"), ("ramps", "floating_panels", "columns", "water_slabs"), ("depth_pass", "rise_fall", "parallax"), ("diagonal_dolly", "wide_crane_rise", "side_tracking_shot"), ("lofi", "frutiger_water"), speed=0.88, structure=1.14),
    _spec("floating_water_panels", "Floating Water Panels", "water_glass", "chrome_dream", "chrome", ("hovering slabs", "liquid panes", "mirror floor", "drift anchors"), ("water_slabs", "floating_panels", "ring_gates", "shards"), ("orbit", "undulate", "lateral_drift"), ("slow_orbit_around_object", "spiral_approach", "close_object_pass"), ("cyber_aero_liquid", "polygon_motion_gallery"), speed=0.82, structure=1.0),
    _spec("corporate_wellness_pool", "Corporate Wellness Pool", "water_glass", "vapor_civic", "plaza", ("wellness pool", "steps", "column lights", "soft walls"), ("water_slabs", "columns", "ramps", "floating_panels"), ("undulate", "long_glide", "rise_fall"), ("long_horizon_glide", "wide_crane_rise", "close_object_pass"), ("lofi", "high_trust_society", "frutiger_water"), speed=0.72, structure=1.02),
    _spec("terminal_reflection_court", "Terminal Reflection Court", "water_glass", "bios_ocean", "atrium", ("reflection court", "glass blocks", "airline boards", "wet floor"), ("water_slabs", "floating_panels", "columns", "signage_blocks"), ("slide_past", "undulate", "parallax"), ("crossing_parallax_pan", "wide_crane_rise", "diagonal_dolly"), ("lofi", "frutiger_water"), speed=0.82, structure=1.08),
    _spec("water_slab_rotunda", "Water Slab Rotunda", "water_glass", "chrome_dream", "chrome", ("rotunda pool", "hover slabs", "circular rails", "misty core"), ("water_slabs", "ring_gates", "columns", "floating_panels"), ("orbit", "undulate", "slow_rotate"), ("slow_orbit_around_object", "spiral_approach", "vertical_elevator_rise"), ("cyber_aero_liquid", "polygon_motion_gallery"), speed=0.78, structure=1.04),
    _spec("aero_bridge_concourse", "Aero Bridge Concourse", "water_glass", "frutiger_aero", "atrium", ("bridge concourse", "glass tubes", "sky panels", "floor reflections"), ("arches", "floating_panels", "rails", "water_slabs"), ("depth_pass", "parallax", "rise_fall"), ("side_tracking_shot", "diagonal_dolly", "wide_crane_rise"), ("lofi", "frutiger_water"), speed=0.88, structure=1.1),
    _spec("indoor_lagoon_axis", "Indoor Lagoon Axis", "water_glass", "sunken_plaza", "submerged", ("indoor lagoon", "glass causeway", "foam bands", "light pylons"), ("water_slabs", "rails", "columns", "ring_gates"), ("undulate", "long_glide", "parallax"), ("long_horizon_glide", "wide_crane_rise", "reverse_pullback"), ("frutiger_water", "lofi"), speed=0.74, structure=1.02),
    _spec("mirror_therapy_chamber", "Mirror Therapy Chamber", "water_glass", "chrome_dream", "chrome", ("therapy mirrors", "pool wedges", "soft pylons", "ripple discs"), ("water_slabs", "shards", "columns", "ring_gates"), ("orbit", "undulate", "rise_fall"), ("slow_orbit_around_object", "close_object_pass", "vertical_elevator_rise"), ("cyber_aero_liquid",), speed=0.74, structure=1.0),
    _spec("glass_planter_walk", "Glass Planter Walk", "water_glass", "frutiger_aero", "atrium", ("planter walk", "glass rails", "blue skylight", "bench cubes"), ("low_poly_plants", "columns", "floating_panels", "water_slabs"), ("parallax", "sway", "slide_past"), ("crossing_parallax_pan", "close_object_pass", "wide_crane_rise"), ("frutiger_water", "lofi"), speed=0.8, structure=1.02),
    _spec("waterwall_data_lounge", "Waterwall Data Lounge", "water_glass", "terminal_mist", "aquarium", ("waterwall lounge", "luminous benches", "floating cards", "glass partitions"), ("water_slabs", "floating_panels", "cuboids", "columns"), ("undulate", "orbit", "slide_past"), ("slow_orbit_around_object", "side_tracking_shot", "close_object_pass"), ("cyber_aero_liquid", "high_trust_society"), speed=0.82, structure=1.02),
    _spec("crystal_bath_court", "Crystal Bath Court", "water_glass", "chrome_dream", "submerged", ("crystal bath", "reflective basin", "glint pillars", "soft fog"), ("shards", "water_slabs", "columns", "ring_gates"), ("undulate", "rise_fall", "orbit"), ("wide_crane_rise", "slow_orbit_around_object", "long_horizon_glide"), ("frutiger_water", "polygon_motion_gallery"), speed=0.7, structure=1.04),
)

CYBER_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("server_cathedral", "Server Cathedral", "ui_computer", "terminal_mist", "corridor", ("server nave", "led columns", "vaulted trays", "cold aisle"), ("cuboids", "columns", "cable_arcs", "floating_panels"), ("depth_pass", "sway", "parallax"), ("low_flythrough", "wide_crane_rise", "vertical_elevator_rise"), ("high_trust_society", "polygon_motion_gallery"), speed=0.92, structure=1.22),
    _spec("cable_trench_corridor", "Cable Trench Corridor", "ui_computer", "terminal_mist", "corridor", ("cable trench", "inspection grates", "maintenance pylons", "service glow"), ("cable_arcs", "rails", "cuboids", "columns"), ("sway", "depth_pass", "slide_past"), ("low_flythrough", "diagonal_dolly", "close_object_pass"), ("high_trust_society", "polygon_motion_gallery"), speed=1.0, structure=1.16),
    _spec("hologram_control_room", "Hologram Control Room", "ui_computer", "neon_nocturne", "map", ("control dais", "floating maps", "holo slabs", "console rings"), ("floating_panels", "ring_gates", "cuboids", "columns"), ("orbit", "slow_rotate", "rise_fall"), ("slow_orbit_around_object", "spiral_approach", "vertical_elevator_rise"), ("cyber_aero_liquid", "bios_dream"), speed=0.86, structure=1.1),
    _spec("crt_archive_chamber", "CRT Archive Chamber", "ui_computer", "bios_ocean", "corridor", ("CRT stacks", "rolling carts", "tube rows", "archive aisles"), ("cuboids", "floating_panels", "columns", "rails"), ("slide_past", "depth_pass", "parallax"), ("side_tracking_shot", "low_flythrough", "reverse_pullback"), ("bios_dream",), speed=0.9, structure=1.18),
    _spec("satellite_uplink_room", "Satellite Uplink Room", "ui_computer", "terminal_mist", "map", ("uplink dishes", "route floor", "signal pylons", "console wedges"), ("antenna_arrays", "ring_gates", "floating_panels", "cuboids"), ("rotate_satellite", "orbit", "parallax"), ("high_overlook_drift", "slow_orbit_around_object", "spiral_approach"), ("bios_dream", "high_trust_society"), speed=0.84, structure=1.12),
    _spec("radar_weather_dome", "Radar Weather Dome", "ui_computer", "frutiger_aero", "map", ("weather dome", "radar rings", "storm map slabs", "monitor plinths"), ("ring_gates", "floating_panels", "columns", "water_slabs"), ("slow_rotate", "orbit", "rise_fall"), ("wide_crane_rise", "spiral_approach", "vertical_elevator_rise"), ("bios_dream", "frutiger_water"), speed=0.8, structure=1.08),
    _spec("neon_vending_alley", "Neon Vending Alley", "cyber_urban", "rain_alley", "city", ("vending walls", "wet signs", "service doors", "back alley towers"), ("signage_blocks", "cuboids", "columns", "water_slabs"), ("slide_past", "parallax", "undulate"), ("close_object_pass", "side_tracking_shot", "low_flythrough"), ("cyber_aero_liquid",), speed=1.0, structure=1.08),
    _spec("datastream_viaduct", "Datastream Viaduct", "ui_computer", "neon_nocturne", "corridor", ("data viaduct", "route rails", "packet gates", "signal fins"), ("rails", "ring_gates", "floating_panels", "towers"), ("depth_pass", "spiral", "slide_past"), ("low_flythrough", "spiral_approach", "crossing_parallax_pan"), ("bios_dream", "polygon_motion_gallery"), speed=1.06, structure=1.2),
    _spec("packet_switch_hall", "Packet Switch Hall", "ui_computer", "terminal_mist", "corridor", ("switch hall", "rack islands", "overhead trays", "fiber lamps"), ("cuboids", "cable_arcs", "columns", "floating_panels"), ("parallax", "sway", "depth_pass"), ("wide_crane_rise", "side_tracking_shot", "vertical_elevator_rise"), ("high_trust_society",), speed=0.92, structure=1.16),
    _spec("orbital_command_walkway", "Orbital Command Walkway", "ui_computer", "bios_ocean", "map", ("command bridge", "angled glass", "route floor", "relay window"), ("floating_panels", "arches", "rails", "ring_gates"), ("orbit", "parallax", "rise_fall"), ("diagonal_dolly", "slow_orbit_around_object", "wide_crane_rise"), ("bios_dream", "cyber_aero_liquid"), speed=0.86, structure=1.1),
    _spec("maintenance_console_cascade", "Maintenance Console Cascade", "ui_computer", "terminal_mist", "corridor", ("console cascade", "staggered desks", "light strips", "service wall"), ("cuboids", "floating_panels", "columns", "signage_blocks"), ("slide_past", "rise_fall", "parallax"), ("crossing_parallax_pan", "close_object_pass", "low_flythrough"), ("high_trust_society",), speed=0.9, structure=1.1),
    _spec("weather_satellite_causeway", "Weather Satellite Causeway", "ui_computer", "frutiger_aero", "map", ("satellite causeway", "orbital maps", "storm pylons", "panel rails"), ("ring_gates", "antenna_arrays", "floating_panels", "rails"), ("rotate_satellite", "orbit", "depth_pass"), ("spiral_approach", "high_overlook_drift", "diagonal_dolly"), ("bios_dream", "polygon_motion_gallery"), speed=0.9, structure=1.14),
    _spec("bios_icon_sanctum", "BIOS Icon Sanctum", "ui_computer", "bios_ocean", "map", ("icon sanctum", "menu monoliths", "glass grids", "floating glyph rails"), ("floating_panels", "columns", "ring_gates", "shards"), ("orbit", "rise_fall", "slow_rotate"), ("vertical_elevator_rise", "slow_orbit_around_object", "wide_crane_rise"), ("bios_dream",), speed=0.78, structure=1.04),
    _spec("signal_bridge_archive", "Signal Bridge Archive", "ui_computer", "bios_ocean", "corridor", ("signal bridge", "archive screens", "route braces", "catwalk rails"), ("floating_panels", "rails", "columns", "cuboids"), ("depth_pass", "parallax", "slide_past"), ("side_tracking_shot", "low_flythrough", "reverse_pullback"), ("bios_dream", "high_trust_society"), speed=0.96, structure=1.12),
    _spec("relay_core_rotunda", "Relay Core Rotunda", "ui_computer", "terminal_mist", "map", ("relay rotunda", "antenna petals", "status rings", "router blocks"), ("ring_gates", "antenna_arrays", "cuboids", "floating_panels"), ("rotate_satellite", "slow_rotate", "orbit"), ("slow_orbit_around_object", "spiral_approach", "vertical_elevator_rise"), ("bios_dream", "high_trust_society"), speed=0.82, structure=1.08),
    _spec("console_rain_arcade", "Console Rain Arcade", "ui_computer", "rain_alley", "city", ("console arcade", "wet terminal booths", "sign ladders", "service shutters"), ("signage_blocks", "cuboids", "floating_panels", "columns"), ("slide_past", "parallax", "undulate"), ("close_object_pass", "crossing_parallax_pan", "side_tracking_shot"), ("cyber_aero_liquid",), speed=0.98, structure=1.06),
)

NATURE_SPACE_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("typhoon_radar_sea", "Typhoon Radar Sea", "nature_weather", "frutiger_aero", "submerged", ("storm sea", "radar rings", "marker buoys", "cloud wall"), ("water_slabs", "ring_gates", "signage_blocks", "columns"), ("undulate", "slow_rotate", "long_glide"), ("long_horizon_glide", "wide_crane_rise", "spiral_approach"), ("frutiger_water",), speed=0.76, structure=1.02),
    _spec("cloud_chamber", "Cloud Chamber", "nature_weather", "frutiger_aero", "space", ("cloud decks", "weather columns", "light wells", "floating slabs"), ("water_slabs", "columns", "floating_panels", "shards"), ("rise_fall", "orbit", "long_glide"), ("wide_crane_rise", "vertical_elevator_rise", "high_overlook_drift"), ("frutiger_water", "camera_direction_gallery"), speed=0.72, structure=0.96),
    _spec("moonlit_reservoir", "Moonlit Reservoir", "nature_weather", "sunken_plaza", "submerged", ("reservoir wall", "moon water", "service lights", "distant towers"), ("water_slabs", "rails", "towers", "columns"), ("undulate", "parallax", "long_glide"), ("long_horizon_glide", "reverse_pullback", "high_overlook_drift"), ("lofi",), speed=0.68, structure=1.04),
    _spec("wireframe_mountain_road", "Wireframe Mountain Road", "nature_weather", "terminal_mist", "highway", ("wire mountains", "road wedge", "guard rails", "ridge sun"), ("rails", "pyramids", "signage_blocks", "columns"), ("depth_pass", "parallax", "long_glide"), ("high_overlook_drift", "wide_crane_rise", "reverse_pullback"), ("night_transit", "polygon_motion_gallery"), speed=0.9, structure=1.1),
    _spec("solar_sail_harbor", "Solar Sail Harbor", "space_cosmic", "bios_ocean", "space", ("sail harbor", "dock rings", "mast arrays", "planet haze"), ("ring_gates", "antenna_arrays", "rails", "floating_panels"), ("slow_rotate", "parallax", "orbit"), ("wide_crane_rise", "slow_orbit_around_object", "high_overlook_drift"), ("lofi", "camera_direction_gallery"), speed=0.76, structure=1.08),
    _spec("orbiting_relay_station", "Orbiting Relay Station", "space_cosmic", "terminal_mist", "space", ("relay station", "dish petals", "truss rings", "signal fins"), ("ring_gates", "antenna_arrays", "shards", "columns"), ("rotate_satellite", "orbit", "spiral"), ("spiral_approach", "slow_orbit_around_object", "vertical_elevator_rise"), ("camera_direction_gallery", "polygon_motion_gallery"), speed=0.82, structure=1.16),
    _spec("polygon_forest_overlook", "Polygon Forest Overlook", "nature_weather", "frutiger_aero", "garden", ("forest slabs", "tree prisms", "ridge path", "sky panels"), ("low_poly_plants", "pyramids", "rails", "floating_panels"), ("sway", "parallax", "long_glide"), ("high_overlook_drift", "wide_crane_rise", "crossing_parallax_pan"), ("lofi", "camera_direction_gallery"), speed=0.74, structure=1.0),
    _spec("rain_on_glass_skyline", "Rain-on-Glass Skyline", "nature_weather", "rain_alley", "city", ("glass rain plane", "skyline bands", "droplet trails", "tower haze"), ("floating_panels", "towers", "water_slabs", "signage_blocks"), ("undulate", "slide_past", "parallax"), ("close_object_pass", "long_horizon_glide", "crossing_parallax_pan"), ("lofi",), speed=0.82, structure=1.02),
    _spec("reservoir_service_road", "Reservoir Service Road", "nature_weather", "sunken_plaza", "highway", ("service road", "water wall", "guard lamps", "dam blocks"), ("rails", "water_slabs", "cuboids", "columns"), ("depth_pass", "undulate", "parallax"), ("diagonal_dolly", "high_overlook_drift", "reverse_pullback"), ("night_transit", "lofi"), speed=0.84, structure=1.08),
    _spec("wind_farm_horizon", "Wind Farm Horizon", "nature_weather", "terminal_mist", "space", ("wind pylons", "service decks", "ridge fog", "warning lights"), ("columns", "shards", "rails", "signage_blocks"), ("slow_rotate", "parallax", "long_glide"), ("long_horizon_glide", "high_overlook_drift", "wide_crane_rise"), ("camera_direction_gallery",), speed=0.72, structure=1.02),
    _spec("tidal_observation_deck", "Tidal Observation Deck", "nature_weather", "sunken_plaza", "plaza", ("tidal deck", "sea rails", "lamp towers", "foam terraces"), ("water_slabs", "rails", "columns", "ramps"), ("undulate", "rise_fall", "parallax"), ("long_horizon_glide", "wide_crane_rise", "crossing_parallax_pan"), ("lofi",), speed=0.72, structure=1.0),
    _spec("stratosphere_garden_ring", "Stratosphere Garden Ring", "space_cosmic", "frutiger_aero", "space", ("garden ring", "petal planters", "planet window", "sky bridges"), ("ring_gates", "low_poly_plants", "floating_panels", "arches"), ("orbit", "rise_fall", "slow_rotate"), ("slow_orbit_around_object", "vertical_elevator_rise", "wide_crane_rise"), ("frutiger_water", "camera_direction_gallery"), speed=0.7, structure=1.02),
    _spec("coastal_radar_cliffs", "Coastal Radar Cliffs", "nature_weather", "bios_ocean", "city", ("radar cliffs", "sea stacks", "dish towers", "storm edge"), ("pyramids", "antenna_arrays", "water_slabs", "towers"), ("sway", "undulate", "parallax"), ("high_overlook_drift", "long_horizon_glide", "reverse_pullback"), ("lofi",), speed=0.74, structure=1.06),
    _spec("wire_valley_switchbacks", "Wire Valley Switchbacks", "nature_weather", "terminal_mist", "highway", ("switchbacks", "terrain grid", "slope lights", "horizon ridges"), ("rails", "pyramids", "columns", "signage_blocks"), ("depth_pass", "parallax", "rise_fall"), ("diagonal_dolly", "high_overlook_drift", "wide_crane_rise"), ("night_transit", "polygon_motion_gallery"), speed=0.88, structure=1.1),
    _spec("orbital_breakwater", "Orbital Breakwater", "space_cosmic", "bios_ocean", "space", ("breakwater ring", "dock fins", "star fog", "relay pylons"), ("ring_gates", "rails", "shards", "antenna_arrays"), ("rotate_satellite", "orbit", "parallax"), ("spiral_approach", "long_horizon_glide", "slow_orbit_around_object"), ("camera_direction_gallery",), speed=0.78, structure=1.08),
    _spec("storm_glass_boardwalk", "Storm Glass Boardwalk", "nature_weather", "frutiger_aero", "plaza", ("glass boardwalk", "storm horizon", "water stripes", "marker lamps"), ("water_slabs", "rails", "floating_panels", "columns"), ("undulate", "slide_past", "long_glide"), ("crossing_parallax_pan", "close_object_pass", "long_horizon_glide"), ("frutiger_water", "lofi"), speed=0.78, structure=1.02),
)

ABSTRACT_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("polyhedron_swarm_corridor", "Polyhedron Swarm Corridor", "abstract_geometry", "chrome_dream", "corridor", ("poly swarm", "deep corridor", "edge glints", "floating solids"), ("prisms", "pyramids", "shards", "ring_gates"), ("spiral", "tumble", "depth_pass"), ("low_flythrough", "spiral_approach", "close_object_pass"), ("polygon_motion_gallery",), speed=1.0, structure=1.14),
    _spec("rotating_prism_plaza", "Rotating Prism Plaza", "abstract_geometry", "vapor_civic", "plaza", ("prism plaza", "rotor solids", "mirror floor", "light seams"), ("prisms", "columns", "water_slabs", "shards"), ("slow_rotate", "orbit", "rise_fall"), ("slow_orbit_around_object", "wide_crane_rise", "vertical_elevator_rise"), ("polygon_motion_gallery", "camera_direction_gallery"), speed=0.82, structure=1.08),
    _spec("low_poly_sculpture_garden", "Low-Poly Sculpture Garden", "abstract_geometry", "frutiger_aero", "garden", ("sculpture garden", "facet hedges", "mirror stones", "sky lawn"), ("prisms", "pyramids", "low_poly_plants", "water_slabs"), ("tumble", "sway", "parallax"), ("high_overlook_drift", "crossing_parallax_pan", "wide_crane_rise"), ("polygon_motion_gallery", "frutiger_water"), speed=0.78, structure=1.0),
    _spec("crystal_tunnel", "Crystal Tunnel", "abstract_geometry", "chrome_dream", "corridor", ("crystal tunnel", "facet ribs", "mirror floor", "glint shards"), ("shards", "ring_gates", "prisms", "rails"), ("depth_pass", "slow_rotate", "spiral"), ("low_flythrough", "spiral_approach", "reverse_pullback"), ("polygon_motion_gallery",), speed=1.02, structure=1.18),
    _spec("ribbon_road", "Ribbon Road", "abstract_geometry", "neon_nocturne", "highway", ("ribbon road", "suspended lanes", "floating markers", "void horizon"), ("rails", "floating_panels", "ring_gates", "shards"), ("depth_pass", "undulate", "parallax"), ("diagonal_dolly", "long_horizon_glide", "low_flythrough"), ("polygon_motion_gallery", "night_transit"), speed=1.04, structure=1.1),
    _spec("floating_cube_city", "Floating Cube City", "abstract_geometry", "terminal_mist", "city", ("cube city", "hover blocks", "void avenues", "light windows"), ("cuboids", "towers", "floating_panels", "rails"), ("lateral_drift", "parallax", "rise_fall"), ("wide_crane_rise", "high_overlook_drift", "crossing_parallax_pan"), ("polygon_motion_gallery",), speed=0.84, structure=1.12),
    _spec("polygon_ring_machine", "Polygon Ring Machine", "abstract_geometry", "chrome_dream", "corridor", ("ring machine", "rotor fins", "facet gates", "engine well"), ("ring_gates", "prisms", "shards", "columns"), ("slow_rotate", "spiral", "depth_pass"), ("spiral_approach", "slow_orbit_around_object", "vertical_elevator_rise"), ("polygon_motion_gallery", "camera_direction_gallery"), speed=0.92, structure=1.16),
    _spec("reflective_shard_basin", "Reflective Shard Basin", "abstract_geometry", "chrome_dream", "chrome", ("shard basin", "mirror water", "facet monoliths", "soft fog"), ("shards", "water_slabs", "columns", "ring_gates"), ("orbit", "undulate", "tumble"), ("slow_orbit_around_object", "close_object_pass", "wide_crane_rise"), ("polygon_motion_gallery",), speed=0.76, structure=1.04),
    _spec("tetrahedron_overlook", "Tetrahedron Overlook", "abstract_geometry", "sunken_plaza", "plaza", ("tetra ridge", "facet skyline", "guard rail", "sea haze"), ("pyramids", "rails", "shards", "water_slabs"), ("tumble", "parallax", "long_glide"), ("high_overlook_drift", "wide_crane_rise", "reverse_pullback"), ("polygon_motion_gallery", "camera_direction_gallery"), speed=0.72, structure=1.08),
    _spec("cube_fountain_axis", "Cube Fountain Axis", "abstract_geometry", "vapor_civic", "plaza", ("cube fountain", "stack solids", "mist jets", "reflection floor"), ("cuboids", "water_slabs", "columns", "shards"), ("rise_fall", "tumble", "parallax"), ("wide_crane_rise", "vertical_elevator_rise", "crossing_parallax_pan"), ("polygon_motion_gallery",), speed=0.8, structure=1.1),
    _spec("shard_rotunda", "Shard Rotunda", "abstract_geometry", "neon_nocturne", "corridor", ("shard rotunda", "facet arch", "core void", "light grooves"), ("shards", "ring_gates", "columns", "prisms"), ("slow_rotate", "orbit", "spiral"), ("spiral_approach", "slow_orbit_around_object", "close_object_pass"), ("polygon_motion_gallery",), speed=0.88, structure=1.12),
    _spec("prism_harbor", "Prism Harbor", "abstract_geometry", "bios_ocean", "space", ("prism harbor", "dock wedges", "sail shards", "star fog"), ("prisms", "rails", "shards", "ring_gates"), ("parallax", "slow_rotate", "long_glide"), ("high_overlook_drift", "wide_crane_rise", "long_horizon_glide"), ("polygon_motion_gallery", "camera_direction_gallery"), speed=0.78, structure=1.06),
    _spec("monolith_switchfield", "Monolith Switchfield", "abstract_geometry", "terminal_mist", "city", ("monolith field", "switch rails", "signal cubes", "void avenue"), ("cuboids", "rails", "columns", "floating_panels"), ("slide_past", "parallax", "rise_fall"), ("crossing_parallax_pan", "reverse_pullback", "wide_crane_rise"), ("polygon_motion_gallery",), speed=0.9, structure=1.12),
    _spec("ring_bridge_cascade", "Ring Bridge Cascade", "abstract_geometry", "frutiger_aero", "atrium", ("ring bridges", "cascade ramps", "glass void", "blue mist"), ("ring_gates", "ramps", "floating_panels", "columns"), ("rise_fall", "orbit", "depth_pass"), ("diagonal_dolly", "spiral_approach", "vertical_elevator_rise"), ("polygon_motion_gallery", "camera_direction_gallery"), speed=0.84, structure=1.08),
    _spec("facet_storm_gallery", "Facet Storm Gallery", "abstract_geometry", "rain_alley", "corridor", ("facet storm", "glint walls", "rotor shards", "wet dark floor"), ("shards", "prisms", "columns", "water_slabs"), ("tumble", "sway", "depth_pass"), ("low_flythrough", "close_object_pass", "side_tracking_shot"), ("polygon_motion_gallery",), speed=0.98, structure=1.1),
    _spec("rotor_cube_observatory", "Rotor Cube Observatory", "abstract_geometry", "bios_ocean", "space", ("rotor cubes", "observation ring", "star floor", "relay braces"), ("cuboids", "ring_gates", "antenna_arrays", "floating_panels"), ("slow_rotate", "orbit", "rise_fall"), ("slow_orbit_around_object", "vertical_elevator_rise", "high_overlook_drift"), ("polygon_motion_gallery", "camera_direction_gallery"), speed=0.8, structure=1.08),
)

ARCHITECTURE_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("glass_bridge_lobby", "Glass Bridge Lobby", "architecture_interior", "vapor_civic", "atrium", ("bridge lobby", "column rhythm", "soft ramps", "reflective floor"), ("columns", "ramps", "floating_panels", "water_slabs"), ("parallax", "rise_fall", "slide_past"), ("wide_crane_rise", "crossing_parallax_pan", "close_object_pass"), ("high_trust_society", "lofi"), speed=0.82, structure=1.12),
    _spec("elevator_core_hotel", "Elevator Core Hotel", "architecture_interior", "vapor_civic", "corridor", ("elevator core", "door bays", "ceiling coffers", "mirror trim"), ("columns", "floating_panels", "ramps", "cuboids"), ("rise_fall", "depth_pass", "parallax"), ("vertical_elevator_rise", "reverse_pullback", "close_object_pass"), ("high_trust_society",), speed=0.84, structure=1.16),
    _spec("atrium_mezzanine_spine", "Atrium Mezzanine Spine", "architecture_interior", "frutiger_aero", "atrium", ("mezzanine spine", "balcony edges", "light strips", "soft planters"), ("columns", "rails", "ramps", "low_poly_plants"), ("side_glide", "parallax", "rise_fall"), ("crossing_parallax_pan", "wide_crane_rise", "diagonal_dolly"), ("high_trust_society", "lofi"), speed=0.82, structure=1.08),
    _spec("courthouse_corridor", "Courthouse Corridor", "architecture_interior", "terminal_mist", "corridor", ("civic corridor", "heavy doors", "wall lamps", "stone rhythm"), ("columns", "cuboids", "arches", "floating_panels"), ("depth_pass", "parallax", "slow_rotate"), ("reverse_pullback", "low_flythrough", "close_object_pass"), ("high_trust_society",), speed=0.8, structure=1.16),
    _spec("wellness_conservatory", "Wellness Conservatory", "architecture_interior", "frutiger_aero", "garden", ("glass conservatory", "pool edge", "soft benches", "plant towers"), ("low_poly_plants", "water_slabs", "columns", "floating_panels"), ("undulate", "sway", "parallax"), ("wide_crane_rise", "high_overlook_drift", "long_horizon_glide"), ("high_trust_society", "frutiger_water"), speed=0.72, structure=1.02),
    _spec("executive_parking_spiral", "Executive Parking Spiral", "architecture_interior", "chrome_dream", "corridor", ("parking spiral", "column drums", "lane arrows", "ceiling ribs"), ("ramps", "columns", "signage_blocks", "rails"), ("depth_pass", "rise_fall", "parallax"), ("spiral_approach", "diagonal_dolly", "reverse_pullback"), ("high_trust_society", "night_transit"), speed=0.94, structure=1.18),
    _spec("fountain_esplanade", "Fountain Esplanade", "architecture_interior", "vapor_civic", "plaza", ("esplanade", "jet basins", "column lights", "civic facade"), ("water_slabs", "columns", "ramps", "towers"), ("jet_pulse", "parallax", "long_glide"), ("wide_crane_rise", "long_horizon_glide", "crossing_parallax_pan"), ("lofi", "high_trust_society"), speed=0.8, structure=1.12),
    _spec("conference_bridge_hall", "Conference Bridge Hall", "architecture_interior", "bios_ocean", "atrium", ("bridge hall", "conference blocks", "window bands", "light coffers"), ("columns", "ramps", "cuboids", "floating_panels"), ("slide_past", "parallax", "rise_fall"), ("side_tracking_shot", "wide_crane_rise", "close_object_pass"), ("high_trust_society",), speed=0.84, structure=1.08),
    _spec("atrium_fountain_tiers", "Atrium Fountain Tiers", "architecture_interior", "vapor_civic", "atrium", ("tier fountain", "stair edges", "glass rails", "light columns"), ("water_slabs", "columns", "ramps", "floating_panels"), ("jet_pulse", "rise_fall", "parallax"), ("vertical_elevator_rise", "wide_crane_rise", "slow_orbit_around_object"), ("lofi", "high_trust_society"), speed=0.78, structure=1.1),
    _spec("lounge_carpet_axis", "Lounge Carpet Axis", "architecture_interior", "rain_alley", "corridor", ("lounge corridor", "carpet stripes", "lamp bays", "low tables"), ("cuboids", "columns", "floating_panels", "rails"), ("depth_pass", "slide_past", "parallax"), ("reverse_pullback", "close_object_pass", "side_tracking_shot"), ("high_trust_society",), speed=0.78, structure=1.14),
)

BRIGHT_SKY_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("floating_sky_plaza", "Floating Sky Plaza", "cyber_urban", "frutiger_aero", "plaza", ("floating civic deck", "bright sky", "glass rails", "sun cloud horizon"), ("floating_panels", "columns", "water_slabs", "ring_gates"), ("long_glide", "parallax", "rise_fall"), ("sweeping_crane_rise", "wide_crane_rise", "pullback_to_city"), ("frutiger_world", "lofi"), speed=0.78, structure=1.04),
    _spec("cloud_garden", "Cloud Garden", "nature_weather", "frutiger_aero", "garden", ("cloud terraces", "sky lawn", "soft trees", "sun planes"), ("low_poly_plants", "water_slabs", "floating_panels", "columns"), ("sway", "rise_fall", "long_glide"), ("high_overlook_drift", "wide_crane_rise", "long_horizon_glide"), ("frutiger_world", "lofi"), speed=0.72, structure=0.98),
    _spec("sunlit_glass_park", "Sunlit Glass Park", "water_glass", "frutiger_aero", "garden", ("glass park", "sunlit slabs", "reflective lawns", "aero windows"), ("floating_panels", "water_slabs", "low_poly_plants", "columns"), ("parallax", "orbit", "rise_fall"), ("diagonal_glass_dolly", "wide_crane_rise", "low_reflective_glide"), ("frutiger_world", "lofi"), speed=0.76, structure=1.02),
    _spec("blue_sky_aero_terminal", "Blue-Sky Aero Terminal", "transit", "frutiger_aero", "transit", ("open terminal deck", "sky walkway", "arrival canopy", "glass gate pylons"), ("rails", "floating_panels", "columns", "water_slabs"), ("depth_pass", "slide_past", "parallax"), ("sweeping_crane_rise", "diagonal_glass_dolly", "side_tracking_shot"), ("frutiger_world", "lofi"), speed=0.88, structure=1.06),
    _spec("white_civic_skybridge", "White Civic Skybridge", "cyber_urban", "vapor_civic", "plaza", ("white bridge deck", "public overlook", "sun columns", "open skyline"), ("columns", "ramps", "floating_panels", "water_slabs"), ("long_glide", "parallax", "rise_fall"), ("pullback_to_city", "wide_crane_rise", "crossing_parallax_pan"), ("frutiger_world", "lofi", "high_trust_society"), speed=0.74, structure=1.08),
)

GREEN_SPACE_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("polygon_grass_field", "Polygon Grass Field", "nature_weather", "frutiger_aero", "garden", ("wide grass field", "low-poly trees", "bright path", "open horizon"), ("low_poly_plants", "pyramids", "water_slabs", "floating_panels"), ("sway", "parallax", "long_glide"), ("low_flythrough", "high_overlook_drift", "wide_crane_rise"), ("frutiger_world", "lofi"), speed=0.74, structure=0.96),
    _spec("cyber_botanical_garden", "Cyber Botanical Garden", "nature_weather", "sunken_plaza", "garden", ("botanical deck", "glass planters", "aqua lawn", "cyber hedges"), ("low_poly_plants", "floating_panels", "columns", "water_slabs"), ("sway", "orbit", "parallax"), ("wide_crane_rise", "diagonal_glass_dolly", "crossing_parallax_pan"), ("frutiger_world", "lofi"), speed=0.76, structure=1.0),
    _spec("low_poly_park_promenade", "Low-Poly Park Promenade", "cyber_urban", "sunken_plaza", "plaza", ("park promenade", "trees", "pool edge", "open civic walk"), ("low_poly_plants", "rails", "water_slabs", "columns"), ("long_glide", "parallax", "sway"), ("long_horizon_glide", "side_tracking_shot", "wide_crane_rise"), ("frutiger_world", "lofi"), speed=0.72, structure=1.0),
    _spec("glass_greenhouse", "Glass Greenhouse", "water_glass", "frutiger_aero", "atrium", ("greenhouse dome", "glass ribs", "plant towers", "wet floor"), ("arches", "floating_panels", "low_poly_plants", "water_slabs"), ("rise_fall", "parallax", "sway"), ("vertical_elevator_rise", "diagonal_glass_dolly", "wide_crane_rise"), ("frutiger_world", "lofi", "frutiger_water"), speed=0.78, structure=1.1),
    _spec("dancing_lawn_plaza", "Dancing Lawn Plaza", "cyber_urban", "vapor_civic", "plaza", ("dancing lawn", "crowd ring", "bright civic grass", "fountain edge"), ("low_poly_plants", "water_slabs", "columns", "ring_gates"), ("rise_fall", "long_glide", "parallax"), ("wide_orbit_core", "wide_crane_rise", "pullback_to_city"), ("frutiger_world", "lofi"), speed=0.84, structure=1.02),
)

WATER_MOTION_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("splash_fountain_court", "Splash Fountain Court", "water_glass", "vapor_civic", "plaza", ("fountain court", "splash arcs", "public steps", "bright water"), ("water_slabs", "columns", "ramps", "floating_panels"), ("jet_pulse", "rise_fall", "parallax"), ("wide_orbit_core", "dive_to_fountain", "wide_crane_rise"), ("frutiger_world", "lofi"), speed=0.86, structure=1.08),
    _spec("water_jet_plaza", "Water Jet Plaza", "water_glass", "vapor_civic", "plaza", ("jet basin", "spray lines", "reflective deck", "sun pillars"), ("water_slabs", "columns", "ring_gates", "floating_panels"), ("jet_pulse", "long_glide", "parallax"), ("wide_crane_rise", "low_reflective_glide", "wide_orbit_core"), ("frutiger_world", "lofi"), speed=0.82, structure=1.06),
    _spec("reflective_pool_garden", "Reflective Pool Garden", "water_glass", "sunken_plaza", "garden", ("mirror pool", "lawn edge", "soft trees", "calm sky"), ("water_slabs", "low_poly_plants", "columns", "floating_panels"), ("undulate", "long_glide", "sway"), ("long_horizon_glide", "wide_crane_rise", "low_reflective_glide"), ("frutiger_world", "lofi"), speed=0.7, structure=1.0),
    _spec("ocean_glass_terrace", "Ocean Glass Terrace", "water_glass", "sunken_plaza", "plaza", ("ocean terrace", "glass balustrade", "wide pool", "sea horizon"), ("water_slabs", "floating_panels", "rails", "columns"), ("undulate", "long_glide", "parallax"), ("horizon_water_drift", "long_horizon_glide", "pullback_to_city"), ("frutiger_world", "lofi"), speed=0.72, structure=1.0),
    _spec("waterfall_atrium", "Waterfall Atrium", "water_glass", "frutiger_aero", "atrium", ("falling water wall", "glass planes", "bridge landings", "pool floor"), ("water_slabs", "columns", "ramps", "floating_panels"), ("undulate", "rise_fall", "parallax"), ("vertical_elevator_rise", "diagonal_glass_dolly", "wide_crane_rise"), ("frutiger_world", "lofi"), speed=0.8, structure=1.12),
)

OUTER_SPACE_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("orbital_garden_station", "Orbital Garden Station", "space_cosmic", "frutiger_aero", "space", ("orbital garden", "planet window", "public deck", "ring habitat"), ("ring_gates", "low_poly_plants", "floating_panels", "arches"), ("orbit", "rise_fall", "slow_rotate"), ("slow_orbit_around_object", "sweeping_panorama_deck", "vertical_elevator_rise"), ("frutiger_world", "lofi"), speed=0.74, structure=1.04),
    _spec("solar_sail_promenade", "Solar Sail Promenade", "space_cosmic", "bios_ocean", "space", ("solar promenade", "sail fins", "observation rails", "planet glow"), ("ring_gates", "rails", "floating_panels", "shards"), ("slow_rotate", "long_glide", "parallax"), ("sweeping_panorama_deck", "high_overlook_drift", "slow_orbit_around_object"), ("frutiger_world", "lofi"), speed=0.76, structure=1.06),
    _spec("planet_view_observation_deck", "Planet-View Observation Deck", "space_cosmic", "vapor_civic", "space", ("observation deck", "planet vista", "glass rails", "calm orbit"), ("rails", "floating_panels", "ring_gates", "columns"), ("orbit", "long_glide", "rise_fall"), ("pullback_to_city", "sweeping_panorama_deck", "slow_orbit_around_object"), ("frutiger_world", "lofi"), speed=0.7, structure=1.02),
    _spec("asteroid_glass_plaza", "Asteroid Glass Plaza", "space_cosmic", "chrome_dream", "space", ("asteroid court", "glass deck", "facet rocks", "ring horizon"), ("shards", "floating_panels", "ring_gates", "water_slabs"), ("orbit", "tumble", "parallax"), ("spiral_approach", "wide_crane_rise", "sweeping_panorama_deck"), ("frutiger_world",), speed=0.82, structure=1.08),
    _spec("moon_pool_with_stars", "Moon Pool with Stars", "space_cosmic", "bios_ocean", "space", ("moon pool", "star water", "planet mist", "quiet deck"), ("water_slabs", "ring_gates", "columns", "floating_panels"), ("undulate", "long_glide", "orbit"), ("horizon_water_drift", "slow_orbit_around_object", "sweeping_panorama_deck"), ("frutiger_world", "lofi"), speed=0.68, structure=1.0),
)

POLYGON_PEOPLE_VARIANTS: tuple[VariantSpec, ...] = (
    _spec("dancing_polygon_crowd", "Dancing Polygon Crowd", "cyber_urban", "vapor_civic", "plaza", ("polygon crowd", "dance ring", "civic floor", "bright sky"), ("ring_gates", "water_slabs", "columns", "floating_panels"), ("rise_fall", "parallax", "orbit"), ("wide_orbit_core", "pullback_people_skyline", "wide_crane_rise"), ("frutiger_world", "lofi"), speed=0.86, structure=1.02),
    _spec("walking_silhouette_commuters", "Walking Silhouette Commuters", "transit", "frutiger_aero", "plaza", ("walking group", "arrival plaza", "open terminal", "glass path"), ("rails", "floating_panels", "columns", "water_slabs"), ("slide_past", "parallax", "long_glide"), ("side_tracking_shot", "diagonal_glass_dolly", "pullback_people_skyline"), ("frutiger_world", "lofi"), speed=0.82, structure=1.0),
    _spec("fountain_plaza_dancers", "Fountain Plaza Dancers", "cyber_urban", "vapor_civic", "plaza", ("fountain dancers", "splash court", "public pillars", "hopeful skyline"), ("water_slabs", "columns", "ring_gates", "floating_panels"), ("jet_pulse", "orbit", "rise_fall"), ("dive_to_fountain", "wide_orbit_core", "sweeping_crane_rise"), ("frutiger_world", "lofi"), speed=0.88, structure=1.06),
    _spec("low_poly_celebration_circle", "Low-Poly Celebration Circle", "cyber_urban", "frutiger_aero", "plaza", ("celebration ring", "grass edge", "soft water", "sun deck"), ("ring_gates", "low_poly_plants", "water_slabs", "columns"), ("orbit", "rise_fall", "parallax"), ("wide_orbit_core", "wide_crane_rise", "pullback_people_skyline"), ("frutiger_world", "lofi"), speed=0.82, structure=1.02),
    _spec("synchronized_cyber_aero_figures", "Synchronized Cyber-Aero Figures", "cyber_urban", "frutiger_aero", "plaza", ("aero figures", "mirror deck", "glass markers", "sky horizon"), ("floating_panels", "water_slabs", "columns", "ring_gates"), ("orbit", "parallax", "rise_fall"), ("wide_orbit_core", "diagonal_glass_dolly", "pullback_people_skyline"), ("frutiger_world", "lofi"), speed=0.8, structure=1.0),
)


GENERATED_VARIANTS: tuple[VariantSpec, ...] = (
    *TRANSIT_VARIANTS,
    *CIVIC_VARIANTS,
    *WATER_GLASS_VARIANTS,
    *CYBER_VARIANTS,
    *NATURE_SPACE_VARIANTS,
    *ABSTRACT_VARIANTS,
    *ARCHITECTURE_VARIANTS,
    *BRIGHT_SKY_VARIANTS,
    *GREEN_SPACE_VARIANTS,
    *WATER_MOTION_VARIANTS,
    *OUTER_SPACE_VARIANTS,
    *POLYGON_PEOPLE_VARIANTS,
)

